
services:
    app:
        build: .
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: postgres_db
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=laravel
            - POSTGRES_PASSWORD=secret
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    postgres_data:
